- Lectures/Lecture 1/readme.md
this is a pull requires someone to review
> modify some text

- Homeworks/HW1/tushar_jain/game_of_life.py
- Homeworks/HW1/tushar_jain/intro.txt
> Hw 1 tushar jain

- Lectures/Lecture 2/1_jupyter_tutorial.ipynb
- Lectures/Lecture 2/2_pandas_series_basics.ipynb
- Lectures/Lecture 2/3_pandas_dataframes_basics.ipynb
- Lectures/Lecture 2/hw2.md
- Lectures/Lecture 2/readme.md
- Lectures/Lecture 2/requirements.txt
> added lecture 2 notes

- Homeworks/HW1/Klim_Yadrintsev/game_of_life.py
- Homeworks/HW1/Klim_Yadrintsev/intro.txt
A Pull request for the working assignment. HW1.
> Finished the Home Work assignment on game of life

- Homeworks/HW1/yiyang_song/game_of_life.py
- Homeworks/HW1/yiyang_song/intro.txt
> submit hw1

- Homeworks/HW1/Dongyu_Wei/game_of_life.py
- Homeworks/HW1/Dongyu_Wei/intro.txt
> add Homeworks/HW1/Dongyu_Wei

- Homeworks/HW1/hong_wang/game_of_life.py
- Homeworks/HW1/hong_wang/intro.txt
Homework 1 hong wang bill
billwanghong93@gmail.com
> Hw 1 hong wang

- Homeworks/HW1/yuan_qin/game_of_life.py
- Homeworks/HW1/yuan_qin/intro.txt
> hw1Yuanqin

- Homeworks/HW1/yige_yang/game_of_life.py
- Homeworks/HW1/yige_yang/intro.txt
Hi, Please review my pull request.
> add my homework

- Homeworks/HW1/YI_SUN/game_of_life.py
- Homeworks/HW1/YI_SUN/intro.txt
> hw_1_yi_sun

- Homeworks/HW1/josephine_he/game_of_life.py
- Homeworks/HW1/josephine_he/intro.txt
Completed hw1 - submitted by Josephine Junyun He
> HW1 completed

- Homeworks/HW1/Anirudh_Tunoori/game_of_life.py
- Homeworks/HW1/Anirudh_Tunoori/intro.txt
> add hw1 files

- Homeworks/HW1/NICOLE_TAN/game_of_life.py
> HW1 Nicole_Tan game_of_life.py

- Homeworks/HW1/Alvin_Yu/game_of_life.py
- Homeworks/HW1/Alvin_Yu/intro.txt
> Hw 1 alvin yu

- Homeworks/HW1/Siddhant_Madan/game_of_life.py
- Homeworks/HW1/Siddhant_Madan/intro.txt
/UCB-MFE-python-preprogram/Homeworks/HW1/Siddhant_Madan
- intro.txt
- game_of_life.py
> hw_1_Siddhant_Madan

- Homeworks/HW1/ARTEM_SHUVALOV/game_of_life.py
- Homeworks/HW1/ARTEM_SHUVALOV/intro.txt
Hello,
Please see commited my solution to the HW1.
Kind regards,
Artem Shuvalov.
> Added solution to the HW1

- Homeworks/HW1/HIMABINDU_ALWAL/game_of_life.py
- Homeworks/HW1/HIMABINDU_ALWAL/intro.txt
Please find my code for HW#1 here
> Hw 1 himabindu alwal

- Homeworks/HW1/Rachel_Cao/game_of_life.py
- Homeworks/HW1/Rachel_Cao/intro.txt
Hello,
This is my first time using git! Hope this works.
Best,
Rachel
> game_of_life.py

- Homeworks/HW2/ARTEM_SHUVALOV/hw_2_artem_shuvalov.ipynb
Hello team,
Please find attached my solution to HW2.
> Added HW2 Solution

- Homeworks/HW2/DAHOU_ZHENG/hw2_dahou_zheng.ipynb
please review my HW2 submission
> hw2 by dahou zheng

- Homeworks/HW2/Dongyu_Wei/hw_2_Dongyu_Wei.ipynb
There is something wrong with my last submit.
> resubmit Hw 2 dongyu wei
